version: 3

dotenv:
  - .secrets/env

tasks:
  dev:api:
    interactive: true
    dir: ./apps/account-registration-api
    cmds:
      - pnpm run build


  acc-registory:app:build:
    interactive: true
    cmds:
      # - pnpm install
      # - pnpm build
      - docker build . -t ghcr.io/kloudlite/account-registration-test:latest -f ./apps/account-registration/Dockerfile

  ac-reg-web:container:build:
    interactive: true
    preconditions:
      - sh: '[[ -n "{{.tag}}" ]]'
        msg: "var tag must have a value"
    vars:
      Image: ghcr.io/kloudlite/account-registration:{{.tag}}
    cmds:
      - docker build . -t {{.Image}} -f apps/account-registration/Dockerfile

  ac-reg-api:container:build:
    interactive: true
    preconditions:
      - sh: '[[ -n "{{.tag}}" ]]'
        msg: "var tag must have a value"
    vars:
      Image: ghcr.io/kloudlite/domain-allocator:{{.tag}}
    cmds:
      - docker build  . -t {{.Image}}

  ac-reg-api:container:push:
    interactive: true
    preconditions:
      - sh: '[[ -n "{{.tag}}" ]]'
        msg: "var tag must have a value"
    vars:
      Image: ghcr.io/kloudlite/domain-allocator:{{.tag}}
    cmds:
      - docker buildx build -t {{.Image}} --platform linux/arm64,linux/amd64 --push .